name: Deploy .NET Application

env:
  AZURE_WEBAPP_NAME: myapp1212    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0'           # set this to the dot net version to use

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on:  windows-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@master
      
      # setup .NET SDK
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build
      - name: restore dependencies and build application
        run: |
          dotnet restore
          dotnet build --no-restore -c Release
          dotnet publish -c Release --no-build -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp 

  deploy:
    needs: build
    runs-on: windows-latest

    environment:
      name: 'Development'
      url: 'https://myapp1212.azurewebsites.net'    
    
    steps:
      # Signing in to Azure
      - name: 'signing in to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Deploy to Azure Web apps
      - name: 'run Azure webapp deploy action using service principal'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      - name: logout
        run: |
          az logout